name: CI

on: [push]

jobs:
  build:
    env:
      key: g++
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Sanitize key
      id: sanitize-key
      run: echo "::set-output name=key::$(echo $key | sed 's/+/plus/g')"  
    - uses: actions/cache@v1
      with:
        key: ${{ steps.sanitize-key.outputs.key }}
        path: .
